timestamp: '2026-05-12T14:13:25.148722'
joints:
  shoulder_pan:
    min:
      ticks: 763
    center:
      ticks: 2114
    max:
      ticks: 3466
  shoulder_lift:
    min:
      ticks: 1035
    center:
      ticks: 2282
    max:
      ticks: 3529
  elbow_flex:
    min:
      ticks: 1168
    center:
      ticks: 2265
    max:
      ticks: 3362
  wrist_flex:
    min:
      ticks: 21
    center:
      ticks: 2056
    max:
      ticks: 4091
  wrist_roll:
    min:
      ticks: 77
    center:
      ticks: 2073
    max:
      ticks: 4069
  gripper:
    min:
      ticks: 30
    center:
      ticks: 2029
    max:
      ticks: 4029
